# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa0fa6496e4c28358f596bdf836d7110ddc32717899406db1908eae326bf54eaad59f0fb5d9ce4919cedfccc820f26f14eede99647120904d8b2454daf9c13b2

test:
  secret_key_base: e9a95fe91d4b73097c95f92300159f3f1a78904af063752efc5f91acf2afd7e69df590d469f637957a94c62e0105ffb475dd8e54d07910ec348865ef622017a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
